spring:
    application:
        name: barber-admin
server:
    port: 9090

#Eureka Client 
eureka:
  client:
    service-url: 
        default-zone: http://localhost:8761/eureka/
    fetch-registry: true    
    register-with-eureka: true
